### ISSUE TITLE
Server down after step 4 of 5

### ISSUE THREAD

**Issue by clica2x** [cpanel/elevate#215] opened 2023-03-23 20:29 UTC
After upgrading from Centos7 to AlmaLinux 8 and all checks were ok, (/scripts/elevate-cpanel --check --upgrade-to=almalinux)
on step 4 the system went to reboot and never come up.
Can not access cpanel or by ssh.
Also can´t submit a ticket to Cpanel because i can not access the "Support Access ID".

Please help,

**Comment by toddr** [comment] 2023-03-23 20:42
Do you have console access or the ability to restore your snapshot to pre-upgrade state?

**Comment by clica2x** [comment] 2023-03-23 21:30
No access, either http or ssh. 
No snapshot. I submitted a ticket at Cpanel support.
1 hour ago i could ping the server with success, but now it seems to be off.

**Comment by sloanebernstein** [comment] 2023-03-23 22:08
Hello,

I'm letting our support department know about your ticket. However, I do want to warn you that unless you can get some kind of access to your system through your hosting provider, perhaps even just filesystem access to your system at the bare minimum through a rescue environment, there isn't much that anyone here or there is going to be able to do for you.

**Comment by sazli** [comment] 2023-03-24 09:51
I think I'm getting the same problem in my own attempt just now ( Didn't come back up after "Rebooting into stage 4 of 5" ). Did you get to fix it? If so, what was the root cause and solution? Thanks.

**Comment by clica2x** [comment] 2023-03-24 10:16
Not fixed. We are waiting their feedback. I will post next updates.

**Comment by toddr** [comment] 2023-03-24 16:32
> I think I'm getting the same problem in my own attempt just now ( Didn't come back up after "Rebooting into stage 4 of 5" ). Did you get to fix it? If so, what was the root cause and solution? Thanks.

@sazli please open a case with support if you are continuing to have issues.

**Comment by atoomic** [comment] 2023-04-13 15:19
Support was provided to customer and issue is now fixed
internal note: view https://cpanel.zendesk.com/agent/tickets/94770212 for more details

**Closed by atoomic** 2023-04-13 15:19 UTC
Labels: cPanel Support

**Comment by lsaguiar** [comment] 2023-05-20 09:33
Hi there,
I'm with the same problem on a production server!!!
Stage 4 failed, I'm trying to reinstall CPANEL but not possible, I can access the server using VNC, please see attached image to try to help me.
![Screenshot 2023-05-20 alle 11 20 37](https://github.com/cpanel/elevate/assets/21153997/b730ae8a-cb86-40b6-80ac-e48561784544)
Any help will be more than welcome.
Many thanks.
Leandro

**Comment by atoomic** [comment] 2023-05-20 14:05
Please open a ticket with cPanel customer support so we can help you.

Thanks

**Comment by lsaguiar** [comment] 2023-05-20 14:10
> Please open a ticket with cPanel customer support so we can help you.
> 
> Thanks

I did already, ticket #95059375

Thanks.
