### ISSUE TITLE
CouchDB repo not supported

### ISSUE THREAD

**Issue by odingalt** [cpanel/elevate#207] opened 2023-03-10 16:56 UTC
root /home/user #/scripts/elevate-cpanel --check --upgrade-to=almalinux
* 2023-03-10 08:47:23 [INFO] Successfully verified signature for cpanel (key types: release).
* 2023-03-10 08:47:40 [WARN] Unsupported YUM repo enabled 'packages-microsoft-com-prod' without packages installed from /etc/yum.repos.d/msprod.repo
* 2023-03-10 08:47:40 [WARN] Unsupported YUM repo enabled 'gitlab_gitlab-ce' without packages installed from /etc/yum.repos.d/gitlab_gitlab-ce.repo
* 2023-03-10 08:47:40 [WARN] Unsupported YUM repo enabled 'couchdb' without packages installed from /etc/yum.repos.d/couchdb.repo
* 2023-03-10 08:47:40 [WARN] *** Elevation Blocker detected: ***

**Comment by toddr** [comment] 2023-03-23 16:06
dupe of #208

**Closed by toddr** 2023-03-23 16:06 UTC
