### ISSUE TITLE
zabbix repo support

### ISSUE THREAD

**Issue by zuckerbrin** [cpanel/elevate#150] opened 2022-11-27 14:16 UTC
info [elevate-cpanel] Successfully verified signature for cpanel (key types: release).
* 27-16:12:36 (3425) [ERROR] 1 package(s) installed from unsupported YUM repo 'zabbix' from /etc/yum.repos.d/zabbix.repo
* 27-16:12:36 (3436) [WARN] Unsupported YUM repo enabled 'zabbix-non-supported' without packages installed from /etc/yum.repos.d/zabbix.repo
* 27-16:12:36 (3374) [INFO] Disabling unused yum repository: zabbix-non-supported
* 27-16:12:36 (3425) [ERROR] 1 package(s) installed from unsupported YUM repo 'zabbix' from /etc/yum.repos.d/zabbix.repo
* 27-16:12:36 (2635) [ERROR] One or more enabled YUM repo are currently unsupported.
You should disable these repositories and remove packages installed from them

**Comment by zuckerbrin** [comment] 2022-11-27 15:13
zabbix.repo was added to VETTED_YUM_REPO block of elevate-cpanel script:
use constant VETTED_YUM_REPO => qw{
CentOS-Base.repo
CentOS-CR.repo
CentOS-Debuginfo.repo
CentOS-fasttrack.repo
CentOS-Media.repo
CentOS-Sources.repo
CentOS-Vault.repo
CentOS-x86_64-kernel.repo
cPAddons.repo
cpanel-plugins.repo
cp-dev-tools.repo
EA4.repo
ELevate.repo
elasticsearch.repo
epel-testing.repo
epel.repo
imunify-rollout.repo
imunify360.repo
influxdb.repo
kernelcare.repo
wp-toolkit-cpanel.repo
imunify360-ea-php-hardened.repo
droplet-agent.repo
zabbix.repo
}

**Comment by toddr** [comment] 2022-11-29 23:06
this is a duplicate of #123

**Closed by toddr** 2022-11-29 23:06 UTC
Labels: Unsupported Repo
