### ISSUE TITLE
ea-php71 showing as blockers when they are no longer installed

### ISSUE THREAD

**Issue by filliph** [cpanel/elevate#159] opened 2022-12-04 17:18 UTC
I'm getting this message when checking for blocker to upgrade CentOS 7 to AlmaLinux:

```
* 04-17:05:06 (2671) [WARN] *** Elevation Blocker detected: ***
One or more EasyApache 4 package(s) are not compatible with AlmaLinux 8.
Please remove these packages before continuing the update.
- ea-openssl-devel
- ea-php71
- ea-php71-libc-client
- ea-php71-pear
- ea-php71-php-bcmath
- ea-php71-php-bz2
- ea-php71-php-calendar
- ea-php71-php-cli
- ea-php71-php-common
- ea-php71-php-curl
- ea-php71-php-devel
- ea-php71-php-exif
- ea-php71-php-fpm
- ea-php71-php-ftp
- ea-php71-php-gd
- ea-php71-php-gettext
- ea-php71-php-gmp
- ea-php71-php-iconv
- ea-php71-php-imap
- ea-php71-php-intl
- ea-php71-php-litespeed
- ea-php71-php-mbstring
- ea-php71-php-mcrypt
- ea-php71-php-mysqlnd
- ea-php71-php-opcache
- ea-php71-php-pdo
- ea-php71-php-posix
- ea-php71-php-soap
- ea-php71-php-sockets
- ea-php71-php-xml
- ea-php71-php-xmlrpc
- ea-php71-php-zip
- ea-php71-runtime


* 04-17:05:06 (692) [WARN] Please fix the detected issues before performing the elevation process.
```

I _did_ have PHP 7.1 installed, but I've since un-provisioned it and switched all legacy sites to run 7.2 instead.

See:
```
root@web02 [~]# yum list installed | grep php71
root@web02 [~]#
```
If I broaden the search to `yum list installed | grep php` this is the output: https://pastebin.com/UtB9kLW5

This is the output of `/usr/local/bin/ea_current_to_profile`: https://pastebin.com/yEaVuuyX

I have also tried rebooting the server, as well as `yum clean all`, to no avail. Presumably, there's some cache that still thinks php-71 is installed. Could you please advise me on how to clear this?

EDIT: In `/opt/cpanel/`, I have `ea-php54`, `ea-php55`, `ea-php56`, `ea-php70` and `ea-php71` folders, though only 7.1 appears to be an issue. Do I need to remove these folders?

**Comment by filliph** [comment] 2022-12-04 17:59
After looking into the code, I found I could run `/scripts/elevate-cpanel --clean` and this has resolved the issue for me - only `ea-openssl-devel` shows as installed which is expected.

Given that the `--check` is intended to refresh the status every time, it might be worth unlinking the `ELEVATE_STAGE_FILE` at the end of the checking process?

**Comment by toddr** [comment] 2022-12-14 23:43
@filliph how did you remove the packages? Through `EasyApache 4` UI or with yum?

**Comment by filliph** [comment] 2022-12-15 00:07
> @filliph how did you remove the packages? Through `EasyApache 4` UI or with yum?

Through EA4.

**Comment by toddr** [comment] 2022-12-15 16:25
Thanks might be a cache we're not clearing. We'll look into it.

**Comment by sloanebernstein** [comment] 2023-05-04 20:20
We were unable to reproduce this issue, and it does not appear, at least given the changes to the code since this issue was first reported, that the issue should even have occurred at all. I am going to close this issue accordingly, but we can re-activate it if another report comes in.

**Closed by sloanebernstein** 2023-05-04 20:20 UTC
Labels: Ready for work
